[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  DATABASE_URL = "postgresql://neondb_owner:npg_PjctZ3bY8vzH@ep-late-king-a71a0chy-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"
  NEXTAUTH_SECRET = "Atj2Dlo0BIbarYvgZQMRGPvJsbt5kE+30FwXFzVpjc0="
  NEXTAUTH_URL = "https://claudemunity.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
